CREATE TABLE 注文.お届け先
(
    注文ID INTEGER NOT NULL PRIMARY KEY,
    郵便番号 VARCHAR(7) NOT NULL,
    住所 VARCHAR (255) NOT NULL,
    電話番号 VARCHAR(20),
    お届け先名 VARCHAR(50),
    登録日時 TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE 注文.お届け先 IS 'お届け先テーブル';
