DROP SCHEMA IF EXISTS 注文 CASCADE;
CREATE SCHEMA 注文;
CREATE SEQUENCE 注文.注文id START 1;

CREATE TABLE 注文.注文
(
    注文ID INTEGER NOT NULL PRIMARY KEY,
    購入者氏名 VARCHAR(50) NOT NULL,
    登録日時 TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE 注文.注文 IS '注文テーブル';

CREATE TABLE 注文.注文明細
(
    注文明細ID SERIAL PRIMARY KEY,
    注文ID INTEGER NOT NULL,
    商品ID INTEGER NOT NULL,
    商品名 VARCHAR(255) NOT NULL,
    度数 VARCHAR(6) NOT NULL,
    単価 INTEGER NOT NULL,
    数量 SMALLINT NOT NULL,
    登録日時 TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE 注文.注文明細 IS '注文明細テーブル';
