DROP SCHEMA IF EXISTS 注文 CASCADE;
CREATE SCHEMA 注文;
CREATE TABLE 注文.お届け先
(
    識別番号 UUID PRIMARY KEY,
    郵便番号 VARCHAR(7) NOT NULL,
    住所 VARCHAR (255) NOT NULL,
    電話番号 VARCHAR(20),
    氏名 VARCHAR(50),
    登録日時 TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP

);

COMMENT ON TABLE 注文.お届け先 IS 'お届け先テーブル';
