CREATE SEQUENCE 注文.注文id START 1;

CREATE TABLE 注文.注文
(
    注文ID SERIAL NOT NULL PRIMARY KEY,
    購入者氏名 VARCHAR(50) NOT NULL,
    登録日時 TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE 注文.注文 IS '注文テーブル';
